version: "3"
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - graphapi
  graphapi:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    command:
      - "--mongo-uri=mongodb://mongodb:27017/movies"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
